import { Dimension } from "../lib/Dimension";

/** Area. Base unit: square meter. */
export const area = new Dimension("area");

export const squareMeter = area.base("squareMeter", {
  symbol: "m²",
  plural: "square meters",
  aliases: ["m2", "square meter"],
});

// Metric multiples/submultiples. Area scales as the square of the length
// prefix, so these can't be generated by the linear SI prefix helper.
export const squareKilometer = area.unit("squareKilometer", 1e6, {
  symbol: "km²",
  aliases: ["km2"],
});
export const hectare = area.unit("hectare", 1e4, { symbol: "ha", plural: "hectares" });
export const are = area.unit("are", 1e2, { plural: "ares" });
export const squareCentimeter = area.unit("squareCentimeter", 1e-4, {
  symbol: "cm²",
  aliases: ["cm2"],
});
export const squareMillimeter = area.unit("squareMillimeter", 1e-6, {
  symbol: "mm²",
  aliases: ["mm2"],
});

// Imperial / US customary.
export const squareInch = area.unit("squareInch", 6.4516e-4, {
  symbol: "in²",
  aliases: ["sq in", "in2"],
});
export const squareFoot = area.unit("squareFoot", 9.290304e-2, {
  symbol: "ft²",
  plural: "square feet",
  aliases: ["sq ft", "ft2"],
});
export const squareYard = area.unit("squareYard", 0.83612736, {
  symbol: "yd²",
  aliases: ["sq yd", "yd2"],
});
export const acre = area.unit("acre", 4046.8564224, { symbol: "ac", plural: "acres" });
export const squareMile = area.unit("squareMile", 2589988.110336, {
  symbol: "mi²",
  aliases: ["sq mi", "mi2"],
});
