import { Dimension } from "../lib/Dimension";

/** Area. Base unit: square meter. */
export const area = new Dimension("area");

export const squareMeter = area.base("squareMeter", ["m²", "m2", "square meter", "square meters"]);

// Metric multiples/submultiples. Area scales as the square of the length
// prefix, so these can't be generated by the linear SI prefix helper.
export const squareKilometer = area.unit("squareKilometer", 1e6, ["km²", "km2"]);
export const hectare = area.unit("hectare", 1e4, ["ha", "hectares"]);
export const are = area.unit("are", 1e2, ["ares"]);
export const squareCentimeter = area.unit("squareCentimeter", 1e-4, ["cm²", "cm2"]);
export const squareMillimeter = area.unit("squareMillimeter", 1e-6, ["mm²", "mm2"]);

// Imperial / US customary.
export const squareInch = area.unit("squareInch", 6.4516e-4, ["sq in", "in²", "in2"]);
export const squareFoot = area.unit("squareFoot", 9.290304e-2, [
  "sq ft",
  "ft²",
  "ft2",
  "square feet",
]);
export const squareYard = area.unit("squareYard", 0.83612736, ["sq yd", "yd²", "yd2"]);
export const acre = area.unit("acre", 4046.8564224, ["ac", "acres"]);
export const squareMile = area.unit("squareMile", 2589988.110336, ["sq mi", "mi²", "mi2"]);
